version: '3.9'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    
    env_file:
      - .env
    
    # or 
    # environment:
      #- BACKEND_PORT=7001   # if you change the port, make sure to also change the VITE_WS_BACKEND_URL at frontend/.env.local
      # - OPENAI_API_KEY=your_openai_api_key
    
    ports:
      - "${BACKEND_PORT:-7001}:${BACKEND_PORT:-7001}"

    command: uvicorn fastapiApp:app --host 0.0.0.0 --port ${BACKEND_PORT:-7001}
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - PORT=5002
      - HOST=0.0.0.0
      - NODE_OPTIONS=--openssl-legacy-provider
    ports:
      - "5002:5002"