version: '1.0'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend

    ports:
      - "${BACKEND_PORT:-7001}:${BACKEND_PORT:-7001}"
    expose:
      - "7001"

    command: uvicorn fastapiApp:app --host 0.0.0.0 --port ${BACKEND_PORT:-7001}
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - PORT=5002
      - HOST=0.0.0.0
      - NODE_OPTIONS=--openssl-legacy-provider
      - VITE_WS_BACKEND_URL=http://backend:7001
    ports:
      - "5002:5002"